---
apiVersion: v1
kind: Namespace
metadata:
  name: sock-shop
  annotations:
    net.beta.kubernetes.io/network-policy: |
      {
        "ingress": {
          "isolation": "DefaultDeny"
        }
      }

---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: kube-system

# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: argocd

---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx

---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana

---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus

---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-metrics