apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: load-test
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: loadtest
  source:
    repoURL: 'https://github.com/tajudeenadedeji/altschool_v2_capstone_project.git'
    path: ./apps/manifests-loadtest
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true