apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-db
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sock-shop
  source:
    repoURL: 'https://github.com/tajudeenadedeji/altschool_capstone_project.git'
    path: ./apps/sock-shop
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
